project_name: la_familia
flutter_version: 3.13.0
dart_version: 3.1.0
platforms:
  - android
  - ios
  - web

custom_code:
  enabled: true
  directories:
    - lib/custom_code

assets:
  enabled: true
  directories:
    - assets/images
    - assets/icons

dependencies:
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  intl: ^0.18.1 