name: la_familia
description: A family task management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.6.0
  image_picker: ^1.1.2  
  video_player: ^2.9.2
  file_picker: ^8.1.2
  assets_audio_player: ^3.1.1
  record: ^5.1.2
  path_provider: ^2.1.4
  google_fonts: ^4.0.3
  fl_chart: 0.68.0
  http: ^1.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/